import js from "@eslint/js";
import jsxA11y from "eslint-plugin-jsx-a11y";
import perfectionist from "eslint-plugin-perfectionist";
import reactCompiler from "eslint-plugin-react-compiler";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import tseslint from "typescript-eslint";

export default tseslint.config(
  {
    ignores: [
      "**/dist",
      "**/build",
      "**/node_modules",
      "scripts/**",
      "**/.astro",
      "apps/marketing/**",
      // Generated by scripts/build-recurrence-wasm.sh (wasm-bindgen glue +
      // embedded engine) — not hand-maintained code.
      "packages/recurrence-wasm/pkg/**",
    ],
  },
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommendedTypeChecked],
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      parserOptions: {
        project: [
          "./apps/desktop/tsconfig.app.json",
          "./apps/desktop/tsconfig.node.json",
          "./packages/core/tsconfig.json",
          "./packages/ui/tsconfig.json",
        ],
        tsconfigRootDir: import.meta.dirname,
      },
    },
    plugins: {
      "jsx-a11y": jsxA11y,
      perfectionist,
      "react-compiler": reactCompiler,
      "react-hooks": reactHooks,
      "react-refresh": reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      ...jsxA11y.configs.recommended.rules,
      "react-hooks/exhaustive-deps": "off",
      // ── jsx-a11y rules deferred to the post-launch a11y backlog (focus management work) ──
      // Re-enable these when the post-launch a11y refactor lands: tab-group/focus-trap components will
      // make the tabindex/autofocus story coherent enough to enforce.
      "jsx-a11y/no-autofocus": "off",
      "jsx-a11y/no-noninteractive-tabindex": "off",
      "perfectionist/sort-imports": [
        "error",
        {
          type: "natural",
          groups: [
            "side-effect",
            "builtin",
            "external",
            "internal",
            ["parent", "sibling", "index"],
            "unknown",
          ],
        },
      ],
      "perfectionist/sort-named-imports": ["error", { type: "natural" }],
      "perfectionist/sort-exports": ["error", { type: "natural" }],
      "perfectionist/sort-objects": ["error", { type: "natural" }],
      "perfectionist/sort-jsx-props": ["error", { type: "natural" }],
      "react-compiler/react-compiler": "error",
      // The React Compiler memoizes for us (see react-compiler/react-compiler
      // above), so hand-written useMemo/useCallback is at best redundant and at
      // worst a stale-closure bug the compiler would not have written. The
      // codebase has zero of them today — this keeps it that way rather than
      // letting the convention live only in the maintainer's head.
      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "react",
              importNames: ["useMemo", "useCallback"],
              message:
                "The React Compiler handles memoization — drop the useMemo/useCallback and write the plain value or function. If a specific hot path really needs manual memoization, suspend this rule inline with a comment saying which measurement justified it.",
            },
          ],
        },
      ],
      // Same convention, the other spelling: no-restricted-imports only sees the
      // import statement, so a namespaced `React.useMemo(...)` would walk past it.
      "no-restricted-syntax": [
        "error",
        {
          selector:
            "MemberExpression[object.name='React'][property.name=/^(useMemo|useCallback)$/]",
          message:
            "The React Compiler handles memoization — drop the React.useMemo/React.useCallback and write the plain value or function.",
        },
      ],
      "react-refresh/only-export-components": ["warn", { allowConstantExport: true }],
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
      "no-console": "error",
    },
  },
  // Tests legitimately spy on console.* (e.g. suppressing React's expected
  // error logs when asserting hooks throw outside their provider).
  {
    files: ["**/*.test.{ts,tsx}", "**/*.spec.{ts,tsx}"],
    rules: {
      "no-console": "off",
    },
  },
  // logger.ts is the single allowed console site — it routes dev output to
  // console.* and prod output to tauri-plugin-log.
  {
    files: ["**/shared/logger.ts"],
    rules: {
      "no-console": "off",
    },
  },
  // shadcn/ui components export CVA variants alongside components — intentional pattern.
  // They also open with the vendored `import * as React from "react"`, which
  // no-restricted-imports flags purely for *containing* useMemo/useCallback in the
  // namespace — nothing here calls them. The namespaced-call half of the ban
  // (no-restricted-syntax, on React.useMemo/React.useCallback) stays on, so the
  // convention is still enforced where it can actually be violated.
  {
    files: ["**/components/ui/**/*.tsx"],
    rules: {
      "no-restricted-imports": "off",
      "react-refresh/only-export-components": "off",
    },
  },
  // Tiptap editor files — moduleResolution: "bundler" prevents ESLint from resolving
  // Tiptap's complex chain/command generics. TypeScript (tsc) resolves them fine.
  // Suppress the false-positive unsafe-* rules for the editor feature directory.
  {
    files: ["**/features/editor/**/*.{ts,tsx}"],
    rules: {
      "@typescript-eslint/no-unsafe-assignment": "off",
      "@typescript-eslint/no-unsafe-call": "off",
      "@typescript-eslint/no-unsafe-member-access": "off",
      "@typescript-eslint/no-unsafe-return": "off",
      "@typescript-eslint/no-unsafe-argument": "off",
    },
  },
  // SlashMenu exports both the React component and tiptap Extension/config from one file
  // (co-location of tightly coupled editor primitives). Fast refresh still works because
  // the extension is not a component — fast-refresh only-export warning is a false positive.
  {
    files: ["**/features/editor/components/SlashMenu.tsx"],
    rules: {
      "react-refresh/only-export-components": "off",
    },
  },
  // Test helpers (test/ + *.test.tsx) — fast-refresh doesn't apply to tests.
  {
    files: ["**/test/**/*.{ts,tsx}", "**/*.test.{ts,tsx}"],
    rules: {
      "react-refresh/only-export-components": "off",
    },
  },
);
