//! Recurrence-rule and schedule commands that are not pure delegation. The
//! declarative half of this module — the twelve pool-and-writer shims — is
//! generated by `db_commands!` and pulled in below, so `db::schedules` still
//! names every schedule command.
use pikos_recurrence::expand_range;
use serde::{Deserialize, Serialize};

pub use super::commands::schedules::*;

/// A visible recurrence rule to expand. The completed/skip exclusion union is
/// kept client-side, so only rule-level EXDATEs travel with the rule here.
#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExpandRuleInput {
    pub rule_id: String,
    pub rrule: String,
    pub scheduled_start: String,
    pub scheduled_end: Option<String>,
    pub rrule_exdates: Vec<String>,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ExpandedOccurrence {
    pub original_date: String,
    pub scheduled_start: String,
    pub scheduled_end: Option<String>,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ExpandedRule {
    pub rule_id: String,
    pub occurrences: Vec<ExpandedOccurrence>,
}

/// Batched raw expansion for the calendar's visible range. Stateless — the
/// caller passes the visible rules, so no DB access. A rule this stricter engine
/// can't parse is OMITTED, not errored, so one out-of-envelope RRULE can't fail
/// the batch (the caller falls back to rrule.js for it). Async so the CPU work
/// runs off the webview's main thread.
#[tauri::command]
pub async fn expand_recurrence_range(
    rules: Vec<ExpandRuleInput>,
    range_start: String,
    range_end: String,
) -> Vec<ExpandedRule> {
    rules
        .into_iter()
        .filter_map(|r| {
            let occurrences = expand_range(
                &r.rrule,
                &r.scheduled_start,
                r.scheduled_end.as_deref(),
                &range_start,
                &range_end,
                &r.rrule_exdates,
            )
            .ok()?;
            Some(ExpandedRule {
                rule_id: r.rule_id,
                occurrences: occurrences
                    .into_iter()
                    .map(|o| ExpandedOccurrence {
                        original_date: o.original_date,
                        scheduled_start: o.scheduled_start,
                        scheduled_end: o.scheduled_end,
                    })
                    .collect(),
            })
        })
        .collect()
}

#[cfg(test)]
mod expand_recurrence_range_tests {
    use super::*;

    fn rule(rule_id: &str, rrule: &str, start: &str) -> ExpandRuleInput {
        ExpandRuleInput {
            rule_id: rule_id.to_string(),
            rrule: rrule.to_string(),
            scheduled_start: start.to_string(),
            scheduled_end: None,
            rrule_exdates: vec![],
        }
    }

    #[tokio::test]
    async fn expands_multiple_rules_keyed_by_id() {
        let out = expand_recurrence_range(
            vec![
                rule("rule-a", "FREQ=WEEKLY;BYDAY=MO", "2026-03-02T09:00:00"),
                rule("rule-b", "FREQ=WEEKLY;BYDAY=WE", "2026-03-04T15:00:00"),
            ],
            "2026-03-09".to_string(),
            "2026-03-16".to_string(),
        )
        .await;

        assert_eq!(out.len(), 2);
        let a = out.iter().find(|r| r.rule_id == "rule-a").unwrap();
        assert_eq!(
            a.occurrences
                .iter()
                .map(|o| o.original_date.as_str())
                .collect::<Vec<_>>(),
            ["2026-03-09"]
        );
        let b = out.iter().find(|r| r.rule_id == "rule-b").unwrap();
        assert_eq!(
            b.occurrences
                .iter()
                .map(|o| o.original_date.as_str())
                .collect::<Vec<_>>(),
            ["2026-03-11"]
        );
    }

    #[tokio::test]
    async fn applies_rule_exdates_but_not_the_completed_skip_union() {
        // Mar 10 drops via the rule's own EXDATE — the completed/skip union isn't
        // part of this input; see `ExpandRuleInput`.
        let mut r = rule("rule-a", "FREQ=DAILY", "2026-03-09T09:00:00");
        r.rrule_exdates = vec!["2026-03-10".to_string()];
        let out =
            expand_recurrence_range(vec![r], "2026-03-09".to_string(), "2026-03-13".to_string())
                .await;

        let dates: Vec<_> = out[0]
            .occurrences
            .iter()
            .map(|o| o.original_date.as_str())
            .collect();
        assert_eq!(dates, ["2026-03-09", "2026-03-11", "2026-03-12"]);
    }

    #[tokio::test]
    async fn omits_an_unparseable_rule_instead_of_erroring_the_batch() {
        // Mirrors the omit-not-error contract documented on `expand_recurrence_range`.
        let out = expand_recurrence_range(
            vec![
                rule("bad", "FREQ=NONSENSE;BYWHATEVER=1", "2026-03-09T09:00:00"),
                rule("good", "FREQ=WEEKLY;BYDAY=MO", "2026-03-09T09:00:00"),
            ],
            "2026-03-09".to_string(),
            "2026-03-16".to_string(),
        )
        .await;

        assert_eq!(out.len(), 1);
        assert_eq!(out[0].rule_id, "good");
    }
}
