// Generated by packages/editor-mobile/scripts/gen-swift-protocol.ts
// Do not edit. Run `pnpm --filter @pikos/editor-mobile gen:swift` after
// changing packages/editor-mobile/src/protocol.ts.
//
// Both halves of the editor bridge come from that one declaration, so the
// webview and the host cannot disagree about a field name or a type. A
// mismatch there would not fail to compile — it would arrive as nil and the
// editor would quietly stop saving.

import Foundation

/// The editor bridge's wire protocol.
public enum EditorBridge {
    /// Version carried on every message.
    ///
    /// On the envelope rather than negotiated once at startup: an app update
    /// can replace the native shell while a webview is still live, so the
    /// receiver needs to be able to reject an individual message it does not
    /// understand instead of misreading it.
    public static let protocolVersion = 1

    // MARK: - Host → webview

    /// Release focus and dismiss the keyboard.
    public struct OutgoingBlurPayload: Codable, Equatable {
        public init() {}
    }

    /// Put the caret in the editor and raise the keyboard.
    public struct OutgoingFocusPayload: Codable, Equatable {
        public init() {}
    }

    /// Insert an image the host has already saved into the workspace. `assetPath`
    /// is the durable reference stored in the document; the webview resolves it for
    /// display.
    public struct OutgoingInsertImagePayload: Codable, Equatable {
        public let assetPath: String

        public init(assetPath: String) {
            self.assetPath = assetPath
        }
    }

    /// Replace the editor's contents with a page's document.
    public struct OutgoingLoadPayload: Codable, Equatable {
        public let doc: String
        public let pageId: String

        public init(doc: String, pageId: String) {
            self.doc = doc
            self.pageId = pageId
        }
    }

    /// Apply the host's colour scheme so the editor matches the app around it.
    public struct OutgoingSetThemePayload: Codable, Equatable {
        public let accent: String
        public let scheme: String

        public init(accent: String, scheme: String) {
            self.accent = accent
            self.scheme = scheme
        }
    }

    /// A message the host sends into the editor.
    ///
    /// Encodes to `{ "v": 1, "type": "...", "payload": { ... } }`.
    public enum Outgoing {
        case blur(OutgoingBlurPayload)
        case focus(OutgoingFocusPayload)
        case insertImage(OutgoingInsertImagePayload)
        case load(OutgoingLoadPayload)
        case setTheme(OutgoingSetThemePayload)

        var messageType: String {
            switch self {
            case .blur: return "blur"
            case .focus: return "focus"
            case .insertImage: return "insertImage"
            case .load: return "load"
            case .setTheme: return "setTheme"
            }
        }

        /// The JSON text to hand to `evaluateJavaScript`.
        public func encoded() throws -> String {
            let encoder = JSONEncoder()
            // Stable key order keeps messages diffable in logs, which matters
            // when debugging a bridge you cannot step through.
            encoder.outputFormatting = [.sortedKeys]

            let payloadData: Data
            switch self {
            case .blur(let p): payloadData = try encoder.encode(p)
            case .focus(let p): payloadData = try encoder.encode(p)
            case .insertImage(let p): payloadData = try encoder.encode(p)
            case .load(let p): payloadData = try encoder.encode(p)
            case .setTheme(let p): payloadData = try encoder.encode(p)
            }

            let payloadJSON = String(decoding: payloadData, as: UTF8.self)
            let escapedType = messageType
            return "{\"v\":\(EditorBridge.protocolVersion),\"type\":\"\(escapedType)\",\"payload\":\(payloadJSON)}"
        }
    }

    // MARK: - Webview → host

    /// The document changed. Debounced in the webview. `plainText` is the extracted
    /// text for the search index, sent alongside so the host does not have to
    /// re-derive it.
    public struct IncomingDocChangedPayload: Codable, Equatable {
        public let doc: String
        public let pageId: String
        public let plainText: String

        public init(doc: String, pageId: String, plainText: String) {
            self.doc = doc
            self.pageId = pageId
            self.plainText = plainText
        }
    }

    /// The content's height in CSS pixels, for hosts sizing the webview inline
    /// rather than letting it scroll itself.
    public struct IncomingHeightChangedPayload: Codable, Equatable {
        public let px: Double

        public init(px: Double) {
            self.px = px
        }
    }

    /// A link was tapped. The webview does not navigate — the host decides whether
    /// to open it.
    public struct IncomingLinkTappedPayload: Codable, Equatable {
        public let url: String

        public init(url: String) {
            self.url = url
        }
    }

    /// The editor has mounted and can accept messages. Carries the protocol version
    /// the webview was built against so the host can refuse a mismatch loudly
    /// rather than misbehave quietly.
    public struct IncomingReadyPayload: Codable, Equatable {
        public let protocolVersion: Double

        public init(protocolVersion: Double) {
            self.protocolVersion = protocolVersion
        }
    }

    /// The user asked to insert an image. The host presents a picker and replies
    /// with insertImage.
    public struct IncomingRequestImagePickerPayload: Codable, Equatable {
        public init() {}
    }

    /// The selection moved. Drives the native formatting toolbar, so it fires on
    /// every selection change and must stay cheap.
    public struct IncomingSelectionChangedPayload: Codable, Equatable {
        public let isEmpty: Bool
        public let marks: [String]
        public let nodeType: String

        public init(isEmpty: Bool, marks: [String], nodeType: String) {
            self.isEmpty = isEmpty
            self.marks = marks
            self.nodeType = nodeType
        }
    }

    /// A message the editor sends to the host.
    public enum Incoming: Decodable {
        case docChanged(IncomingDocChangedPayload)
        case heightChanged(IncomingHeightChangedPayload)
        case linkTapped(IncomingLinkTappedPayload)
        case ready(IncomingReadyPayload)
        case requestImagePicker(IncomingRequestImagePickerPayload)
        case selectionChanged(IncomingSelectionChangedPayload)

        private enum CodingKeys: String, CodingKey {
            case v, type, payload
        }

        public enum DecodingFailure: Error, Equatable {
            /// The webview speaks a protocol version this build does not.
            case unsupportedVersion(Int)
            /// A message type this build does not know.
            case unknownType(String)
        }

        public init(from decoder: Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)

            let version = try container.decode(Int.self, forKey: .v)
            guard version == EditorBridge.protocolVersion else {
                throw DecodingFailure.unsupportedVersion(version)
            }

            let type = try container.decode(String.self, forKey: .type)
            switch type {
            case "docChanged":
                return .docChanged(try container.decode(IncomingDocChangedPayload.self, forKey: .payload))
            case "heightChanged":
                return .heightChanged(try container.decode(IncomingHeightChangedPayload.self, forKey: .payload))
            case "linkTapped":
                return .linkTapped(try container.decode(IncomingLinkTappedPayload.self, forKey: .payload))
            case "ready":
                return .ready(try container.decode(IncomingReadyPayload.self, forKey: .payload))
            case "requestImagePicker":
                return .requestImagePicker(try container.decode(IncomingRequestImagePickerPayload.self, forKey: .payload))
            case "selectionChanged":
                return .selectionChanged(try container.decode(IncomingSelectionChangedPayload.self, forKey: .payload))
            default:
                throw DecodingFailure.unknownType(type)
            }
        }
    }
}
