// The hand-written types and the ones generated from the Rust wire structs must
// describe the same shape. Assignability is asserted in both directions, so a field
// added, removed, renamed or re-nulled on either side stops compiling — which is what
// lets `types.ts`, `storage.ts` and `pikos-db` be edited independently without
// drifting. `exactOptionalPropertyTypes` makes optional-vs-nullable a difference too.
//
// A failure here is not an assertion to relax: one of the two sides is lying about
// what the backend sends. Fix that side, then run scripts/gen-ts-bindings.sh.

import type { CompleteRecurringInput as GCompleteInput } from "./generated/CompleteRecurringInput";
import type { FolderUpdate as GFolderUpdate } from "./generated/FolderUpdate";
import type { NewFolder as GNewFolder } from "./generated/NewFolder";
import type { NewPage as GNewPage } from "./generated/NewPage";
import type { NewPageSchedule as GNewSchedule } from "./generated/NewPageSchedule";
import type { NewRecurrenceRule as GNewRule } from "./generated/NewRecurrenceRule";
import type { PageScheduleUpdate as GScheduleUpdate } from "./generated/PageScheduleUpdate";
import type { PageUpdate as GPageUpdate } from "./generated/PageUpdate";
import type { RecurrenceRuleUpdate as GRuleUpdate } from "./generated/RecurrenceRuleUpdate";
import type { SkipOccurrenceInput as GSkipInput } from "./generated/SkipOccurrenceInput";
import type {
  FolderUpdate,
  NewFolder,
  NewPage,
  NewPageSchedule,
  NewRecurrenceRule,
  PageScheduleUpdate,
  PageUpdate,
  RecurrenceRuleUpdate,
} from "./storage";
import type { CompleteRecurringInput, SkipOccurrenceInput } from "./types";

/** `never` unless the two types accept each other, which `Assert` then rejects. */
type Mutual<A, B> = [A] extends [B] ? ([B] extends [A] ? true : never) : never;
type Assert<T extends true> = T;

// The entities are re-exported from ./generated by types.ts, so they are identical by
// construction. What still needs asserting is the input side, where TS derives its
// shapes from the entities (Omit/Partial) while Rust declares them as separate structs.
export type NewPageConforms = Assert<Mutual<NewPage, GNewPage>>;
export type PageUpdateConforms = Assert<Mutual<PageUpdate, GPageUpdate>>;
export type NewFolderConforms = Assert<Mutual<NewFolder, GNewFolder>>;
export type FolderUpdateConforms = Assert<Mutual<FolderUpdate, GFolderUpdate>>;
export type NewScheduleConforms = Assert<Mutual<NewPageSchedule, GNewSchedule>>;
export type ScheduleUpdateConforms = Assert<Mutual<PageScheduleUpdate, GScheduleUpdate>>;
export type NewRuleConforms = Assert<Mutual<NewRecurrenceRule, GNewRule>>;
export type RuleUpdateConforms = Assert<Mutual<RecurrenceRuleUpdate, GRuleUpdate>>;
export type CompleteInputConforms = Assert<Mutual<CompleteRecurringInput, GCompleteInput>>;
export type SkipInputConforms = Assert<Mutual<SkipOccurrenceInput, GSkipInput>>;
