//! Parity tests for the calendar layout port.
//!
//! Corpus generated by `apps/desktop/scripts/gen-calendar-parity.ts`; regenerate
//! with `pnpm --filter @pikos/desktop gen:parity`.
//!
//! Only the pixel-independent half of calendar layout is compared, because only
//! that half is ported — see `pikos_core::calendar` for what is excluded and
//! why. The generator itself refuses to emit a corpus unless cascade depth is
//! identical across all three rendering densities, so a corpus existing at all
//! is evidence that the thing being compared here is genuinely portable.

use std::collections::BTreeMap;
use std::fs;
use std::path::PathBuf;

use pikos_core::calendar::all_day::{
    assign_stable_all_day_rows, build_all_day_bars, crossing_midnights_count,
};
use pikos_core::calendar::timed::assign_timed_columns;
use pikos_core::calendar::LayoutPage;
use pikos_core::dates::parse_local_iso;
use serde::Deserialize;

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct CorpusPage {
    id: String,
    created_at: String,
    scheduled_start: Option<String>,
    scheduled_end: Option<String>,
}

impl From<&CorpusPage> for LayoutPage {
    fn from(p: &CorpusPage) -> Self {
        LayoutPage {
            id: p.id.clone(),
            created_at: p.created_at.clone(),
            scheduled_start: p.scheduled_start.clone(),
            scheduled_end: p.scheduled_end.clone(),
        }
    }
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct ExpectedBlock {
    page_id: String,
    cascade_depth: usize,
    is_continuation_before: bool,
    is_continuation_after: bool,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct TimedScenario {
    id: String,
    note: String,
    day: String,
    pages: Vec<CorpusPage>,
    blocks: Vec<ExpectedBlock>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct ExpectedBar {
    page_id: String,
    start_col: usize,
    span: usize,
    row: usize,
    continues_left: bool,
    continues_right: bool,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct AllDayScenario {
    id: String,
    note: String,
    days: Vec<String>,
    pages: Vec<CorpusPage>,
    bars: Vec<ExpectedBar>,
    row_count: usize,
    /// Per day, per row: the page id occupying that slot, or null.
    slots: Vec<Vec<Option<String>>>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct MidnightCase {
    id: String,
    start: String,
    end: String,
    count: u32,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct CalendarCorpus {
    timed: Vec<TimedScenario>,
    all_day: Vec<AllDayScenario>,
    midnights: Vec<MidnightCase>,
}

fn load() -> CalendarCorpus {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/corpus/calendar.json");
    let raw = fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!(
            "cannot read {}: {e}\nGenerate it with `pnpm --filter @pikos/desktop gen:parity`.",
            path.display()
        )
    });
    serde_json::from_str(&raw).unwrap_or_else(|e| panic!("corpus schema mismatch: {e}"))
}

#[test]
fn timed_column_assignment_matches_typescript() {
    let corpus = load();
    assert!(
        !corpus.timed.is_empty(),
        "corpus carries no timed scenarios"
    );

    for scenario in &corpus.timed {
        let pages: Vec<LayoutPage> = scenario.pages.iter().map(LayoutPage::from).collect();
        let actual = assign_timed_columns(&pages, &scenario.day);

        // Keyed, not positional: the TS side emits in DOM paint order, which is
        // pixel-derived and deliberately not reproduced. What must match is
        // which column each page lands in.
        let actual_map: BTreeMap<&str, (usize, bool, bool)> = actual
            .iter()
            .map(|b| {
                (
                    b.page_id.as_str(),
                    (
                        b.cascade_depth,
                        b.is_continuation_before,
                        b.is_continuation_after,
                    ),
                )
            })
            .collect();
        let expected_map: BTreeMap<&str, (usize, bool, bool)> = scenario
            .blocks
            .iter()
            .map(|b| {
                (
                    b.page_id.as_str(),
                    (
                        b.cascade_depth,
                        b.is_continuation_before,
                        b.is_continuation_after,
                    ),
                )
            })
            .collect();

        assert_eq!(
            expected_map, actual_map,
            "timed scenario `{}` diverged ({})",
            scenario.id, scenario.note
        );
    }
}

#[test]
fn all_day_rows_and_bars_match_typescript() {
    let corpus = load();
    assert!(
        !corpus.all_day.is_empty(),
        "corpus carries no all-day scenarios"
    );

    for scenario in &corpus.all_day {
        let pages: Vec<LayoutPage> = scenario.pages.iter().map(LayoutPage::from).collect();
        let slots = assign_stable_all_day_rows(&pages, &scenario.days);

        let actual_slots: Vec<Vec<Option<String>>> = slots
            .iter()
            .map(|day| {
                day.iter()
                    .map(|s| s.as_ref().map(|i| i.page_id.clone()))
                    .collect()
            })
            .collect();

        assert_eq!(
            scenario.slots, actual_slots,
            "all-day scenario `{}` slot grid diverged ({})",
            scenario.id, scenario.note
        );

        let actual_row_count = slots.first().map_or(0, |d| d.len());
        assert_eq!(
            scenario.row_count, actual_row_count,
            "all-day scenario `{}` row count diverged",
            scenario.id
        );

        let bars = build_all_day_bars(&slots);
        assert_eq!(
            scenario.bars.len(),
            bars.len(),
            "all-day scenario `{}` bar count diverged ({})\n  TS:   {:?}\n  Rust: {:?}",
            scenario.id,
            scenario.note,
            scenario
                .bars
                .iter()
                .map(|b| (&b.page_id, b.row, b.start_col, b.span))
                .collect::<Vec<_>>(),
            bars.iter()
                .map(|b| (&b.page_id, b.row, b.start_col, b.span))
                .collect::<Vec<_>>(),
        );

        for (n, (exp, act)) in scenario.bars.iter().zip(bars.iter()).enumerate() {
            assert_eq!(exp.page_id, act.page_id, "{}[{n}]: pageId", scenario.id);
            assert_eq!(exp.row, act.row, "{}[{n}]: row", scenario.id);
            assert_eq!(
                exp.start_col, act.start_col,
                "{}[{n}]: startCol",
                scenario.id
            );
            assert_eq!(exp.span, act.span, "{}[{n}]: span", scenario.id);
            assert_eq!(
                exp.continues_left, act.continues_left,
                "{}[{n}]: continuesLeft",
                scenario.id
            );
            assert_eq!(
                exp.continues_right, act.continues_right,
                "{}[{n}]: continuesRight",
                scenario.id
            );
        }
    }
}

#[test]
fn midnight_crossing_matches_typescript() {
    let corpus = load();
    for case in &corpus.midnights {
        let start = parse_local_iso(&case.start).expect("corpus start parses");
        let end = parse_local_iso(&case.end).expect("corpus end parses");
        assert_eq!(
            case.count,
            crossing_midnights_count(&start, &end),
            "midnight case `{}` diverged",
            case.id
        );
    }
}

/// Recurring virtual occurrences share their head page's id while being
/// single-day events. Two independent things must hold: rows claim only the
/// days actually occupied (so an unrelated event in a gap day is not pushed
/// down), and bars never coalesce across the gaps. Both are easy to break with
/// a plausible "simplification" to range-based claiming, so they are asserted
/// directly rather than left to the generic comparison.
#[test]
fn shared_id_virtuals_neither_claim_gaps_nor_coalesce() {
    let corpus = load();
    let scenario = corpus
        .all_day
        .iter()
        .find(|s| s.id == "non_contiguous_shared_id")
        .expect("corpus must carry the shared-id fixture");

    let pages: Vec<LayoutPage> = scenario.pages.iter().map(LayoutPage::from).collect();
    let slots = assign_stable_all_day_rows(&pages, &scenario.days);
    let bars = build_all_day_bars(&slots);

    let mwf: Vec<_> = bars.iter().filter(|b| b.page_id == "mwf").collect();
    assert_eq!(
        mwf.len(),
        3,
        "M/W/F virtuals coalesced into {} bar(s) instead of staying separate",
        mwf.len()
    );
    assert!(
        mwf.iter().all(|b| b.span == 1),
        "a single-day virtual produced a multi-day bar: {mwf:?}"
    );

    let tue = bars
        .iter()
        .find(|b| b.page_id == "tue")
        .expect("the gap-day event must still be placed");
    assert_eq!(
        tue.row, 0,
        "the gap-day event was pushed to row {} — the M/W/F span claimed days it does not occupy",
        tue.row
    );
}
