//! Parity tests for deep links, schedule transitions and text extraction.
//!
//! Corpora: `platform.json` (generated by the desktop app, since deep-link and
//! schedule logic live there) and `text.json` (generated by @pikos/core).
//! Regenerate with `pnpm --filter @pikos/desktop gen:parity` and
//! `pnpm --filter @pikos/core gen:parity` respectively.

use std::fs;
use std::path::PathBuf;

use pikos_core::deep_link::{parse_deep_link, DeepLink};
use pikos_core::schedule::{compute_schedule_transition, normalize_end_input};
use pikos_core::text::extract_text;
use serde::Deserialize;

fn load<T: for<'de> Deserialize<'de>>(name: &str) -> T {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/corpus")
        .join(name);
    let raw = fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!(
            "cannot read {}: {e}\nRegenerate the corpus.",
            path.display()
        )
    });
    serde_json::from_str(&raw).unwrap_or_else(|e| panic!("corpus schema mismatch in {name}: {e}"))
}

// ─── Deep links ──────────────────────────────────────────────────────────────

/// Mirrors the TypeScript `DeepLinkAction` union as the generator serialises
/// it: an internally-tagged object, or null.
#[derive(Debug, Deserialize)]
#[serde(tag = "type", rename_all = "kebab-case")]
enum ExpectedAction {
    Page {
        #[serde(rename = "pageId")]
        page_id: String,
    },
    View {
        #[serde(rename = "viewId")]
        view_id: String,
    },
    Calendar,
    QuickAdd {
        prefill: String,
    },
    Search {
        prefill: String,
    },
}

#[derive(Debug, Deserialize)]
struct DeepLinkCase {
    url: String,
    action: Option<ExpectedAction>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct PlatformCorpus {
    deep_links: Vec<DeepLinkCase>,
    schedule_transitions: Vec<ScheduleCase>,
    normalize_ends: Vec<NormalizeCase>,
}

#[derive(Debug, Deserialize)]
struct ScheduleCase {
    id: String,
    start: Option<String>,
    end: Option<String>,
    iso: String,
    result: ScheduleResult,
}

#[derive(Debug, Deserialize)]
struct ScheduleResult {
    start: String,
    end: Option<String>,
}

#[derive(Debug, Deserialize)]
struct NormalizeCase {
    id: String,
    start: String,
    end: Option<String>,
    result: Option<String>,
}

fn matches(expected: &ExpectedAction, actual: &DeepLink) -> bool {
    match (expected, actual) {
        (ExpectedAction::Page { page_id }, DeepLink::Page { page_id: a }) => page_id == a,
        (ExpectedAction::View { view_id }, DeepLink::View { view_id: a }) => view_id == a.as_str(),
        (ExpectedAction::Calendar, DeepLink::Calendar) => true,
        (ExpectedAction::QuickAdd { prefill }, DeepLink::QuickAdd { prefill: a }) => prefill == a,
        (ExpectedAction::Search { prefill }, DeepLink::Search { prefill: a }) => prefill == a,
        _ => false,
    }
}

#[test]
fn deep_links_match_typescript() {
    let corpus: PlatformCorpus = load("platform.json");
    assert!(!corpus.deep_links.is_empty());

    for case in &corpus.deep_links {
        let actual = parse_deep_link(&case.url);
        match (&case.action, &actual) {
            (None, None) => {}
            (Some(exp), Some(act)) => assert!(
                matches(exp, act),
                "deep link `{}` diverged\n  TS:   {exp:?}\n  Rust: {act:?}",
                case.url
            ),
            (None, Some(act)) => {
                panic!(
                    "deep link `{}`: TS rejected it, Rust returned {act:?}",
                    case.url
                )
            }
            (Some(exp), None) => {
                panic!(
                    "deep link `{}`: TS returned {exp:?}, Rust rejected it",
                    case.url
                )
            }
        }
    }
}

/// Query values arrive percent-encoded from the OS. Decoding them differently
/// from desktop would silently mangle a quick-add prefill containing a space or
/// a `#tag`, which is exactly what quick-add links carry.
#[test]
fn deep_link_query_values_are_percent_decoded() {
    let link = parse_deep_link("pikos://quick-add?text=tomorrow%20at%203pm%20%23work")
        .expect("quick-add link parses");
    assert_eq!(
        link,
        DeepLink::QuickAdd {
            prefill: "tomorrow at 3pm #work".to_string()
        }
    );
}

// ─── Schedule transitions ────────────────────────────────────────────────────

#[test]
fn schedule_transitions_match_typescript() {
    let corpus: PlatformCorpus = load("platform.json");
    assert!(!corpus.schedule_transitions.is_empty());

    for case in &corpus.schedule_transitions {
        let actual =
            compute_schedule_transition(case.start.as_deref(), case.end.as_deref(), &case.iso);
        assert_eq!(
            case.result.start, actual.start,
            "transition `{}`: start diverged",
            case.id
        );
        assert_eq!(
            case.result.end, actual.end,
            "transition `{}`: end diverged",
            case.id
        );
    }
}

#[test]
fn normalize_end_matches_typescript() {
    let corpus: PlatformCorpus = load("platform.json");
    for case in &corpus.normalize_ends {
        let actual = normalize_end_input(&case.start, case.end.as_deref());
        assert_eq!(case.result, actual, "normalizeEnd `{}` diverged", case.id);
    }
}

// ─── extractText ─────────────────────────────────────────────────────────────

#[derive(Debug, Deserialize)]
#[serde(untagged)]
enum Captured<T> {
    Ok { value: T },
    Err { error: String },
}

#[derive(Debug, Deserialize)]
struct ExtractCase {
    id: String,
    doc: String,
    text: Captured<String>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct TextCorpus {
    extract_text_cases: Vec<ExtractCase>,
}

#[test]
fn extract_text_matches_typescript() {
    let corpus: TextCorpus = load("text.json");
    assert!(!corpus.extract_text_cases.is_empty());

    for case in &corpus.extract_text_cases {
        let expected = match &case.text {
            Captured::Ok { value } => value,
            Captured::Err { error } => panic!(
                "extractText case `{}` records a TS failure, so there is nothing to \
                 compare against: {error}",
                case.id
            ),
        };
        assert_eq!(
            expected,
            &extract_text(&case.doc),
            "extractText `{}` diverged",
            case.id
        );
    }
}

/// Malformed content must never panic. A page whose JSON is corrupt should
/// still open with an empty search index, not take the app down — the same
/// contract the TypeScript documents.
#[test]
fn extract_text_never_panics_on_garbage() {
    for input in [
        "",
        "{}",
        "[",
        "{\"content\":",
        "\u{0}\u{1}\u{2}",
        "{\"content\":[{\"content\":[]}]}",
        "{\"text\":123}",
        "{\"content\":\"not an array\"}",
    ] {
        let _ = extract_text(input);
    }
}
