// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(pikos_ffiFFI)
import pikos_ffiFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_pikos_ffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_pikos_ffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }

    init(rawBufferPointer: UnsafeRawBufferPointer) {
        self.init(
            len: Int32(rawBufferPointer.count),
            data: rawBufferPointer.baseAddress?.assumingMemoryBound(to: UInt8.self)
        )
    }
}

// Converter for `&[u8]` / `[ByRef] bytes` arguments.
//
// Conforms to `FfiConverter` so the compiler enforces the full converter
// method set. Only the scope-bound `lower(_:_body:)` overload is sound —
// zero-copy byte buffers only flow foreign -> Rust, and only in argument
// position. The four protocol-witness methods (`lift`, `lower`, `read`,
// `write`) `fatalError` at runtime if anyone reaches them.
//
// The scope-bound `lower` takes a closure because the `ForeignBytes`
// pointer is only guaranteed valid for the duration of
// `Data.withUnsafeBytes`. Callers must run the full FFI call inside
// the closure body.
fileprivate enum FfiConverterByRefBytes: FfiConverter {
    typealias SwiftType = Data
    typealias FfiType = ForeignBytes

    static func lower<R>(_ value: Data, _ body: (ForeignBytes) throws -> R) rethrows -> R {
        return try value.withUnsafeBytes { rawBuf in
            try body(ForeignBytes(rawBufferPointer: rawBuf))
        }
    }

    static func lower(_ value: Data) -> ForeignBytes {
        fatalError("ByRef bytes cannot use the plain lower: returning ForeignBytes escapes the Data.withUnsafeBytes scope. Use the scope-bound lower(_:_body:) overload instead.")
    }

    static func lift(_ value: ForeignBytes) throws -> Data {
        fatalError("ByRef bytes cannot be lifted: zero-copy &[u8] only flows foreign->Rust")
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        fatalError("ByRef bytes cannot be read from a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")
    }

    static func write(_ value: Data, into buf: inout [UInt8]) {
        fatalError("ByRef bytes cannot be written to a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsurePikosFfiInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt64: FfiConverterPrimitive {
    typealias FfiType = Int64
    typealias SwiftType = Int64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int64, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        // Use Swift's native UTF-8 decoder; `String(bytes:encoding:.utf8)` goes
        // through Foundation's NSString and silently strips a leading U+FEFF BOM.
        // Invalid UTF-8 substitutes U+FFFD instead of trapping (unreachable
        // given Rust's `String` invariant).
        return String(decoding: bytes, as: UTF8.self)
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        // See `lift` above for why we avoid Foundation's NSString-backed decoder here.
        return String(decoding: try readBytes(&buf, count: Int(len)), as: UTF8.self)
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}


/**
 * A contiguous run of one all-day page across visible columns, in one row.
 */
public struct AllDayBar: Equatable, Hashable {
    public var pageId: String
    public var startCol: UInt32
    public var span: UInt32
    public var row: UInt32
    /**
     * The event begins before the visible range — cut the leading edge.
     */
    public var continuesLeft: Bool
    /**
     * The event ends after the visible range — cut the trailing edge.
     */
    public var continuesRight: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(pageId: String, startCol: UInt32, span: UInt32, row: UInt32, 
        /**
         * The event begins before the visible range — cut the leading edge.
         */continuesLeft: Bool, 
        /**
         * The event ends after the visible range — cut the trailing edge.
         */continuesRight: Bool) {
        self.pageId = pageId
        self.startCol = startCol
        self.span = span
        self.row = row
        self.continuesLeft = continuesLeft
        self.continuesRight = continuesRight
    }

    

    
}

#if compiler(>=6)
extension AllDayBar: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAllDayBar: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AllDayBar {
        return
            try AllDayBar(
                pageId: FfiConverterString.read(from: &buf), 
                startCol: FfiConverterUInt32.read(from: &buf), 
                span: FfiConverterUInt32.read(from: &buf), 
                row: FfiConverterUInt32.read(from: &buf), 
                continuesLeft: FfiConverterBool.read(from: &buf), 
                continuesRight: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: AllDayBar, into buf: inout [UInt8]) {
        FfiConverterString.write(value.pageId, into: &buf)
        FfiConverterUInt32.write(value.startCol, into: &buf)
        FfiConverterUInt32.write(value.span, into: &buf)
        FfiConverterUInt32.write(value.row, into: &buf)
        FfiConverterBool.write(value.continuesLeft, into: &buf)
        FfiConverterBool.write(value.continuesRight, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAllDayBar_lift(_ buf: RustBuffer) throws -> AllDayBar {
    return try FfiConverterTypeAllDayBar.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAllDayBar_lower(_ value: AllDayBar) -> RustBuffer {
    return FfiConverterTypeAllDayBar.lower(value)
}


/**
 * The subset of a page the layout algorithms read.
 *
 * Mirrors `pikos_core::calendar::LayoutPage`. Duplicated rather than exported
 * directly so the FFI surface can evolve without forcing a change on the core
 * type, and so Swift never sees a field it has no use for.
 */
public struct LayoutPage: Equatable, Hashable {
    public var id: String
    /**
     * Stable tiebreaker for equal-length all-day spans. Page ids are UUIDs, so
     * ordering by them alone would be arbitrary rather than meaningful.
     */
    public var createdAt: String
    /**
     * `YYYY-MM-DD` (all-day) or `YYYY-MM-DDTHH:MM:SS` (timed); `None` when the
     * page is unscheduled.
     */
    public var scheduledStart: String?
    public var scheduledEnd: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, 
        /**
         * Stable tiebreaker for equal-length all-day spans. Page ids are UUIDs, so
         * ordering by them alone would be arbitrary rather than meaningful.
         */createdAt: String, 
        /**
         * `YYYY-MM-DD` (all-day) or `YYYY-MM-DDTHH:MM:SS` (timed); `None` when the
         * page is unscheduled.
         */scheduledStart: String?, scheduledEnd: String?) {
        self.id = id
        self.createdAt = createdAt
        self.scheduledStart = scheduledStart
        self.scheduledEnd = scheduledEnd
    }

    

    
}

#if compiler(>=6)
extension LayoutPage: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeLayoutPage: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> LayoutPage {
        return
            try LayoutPage(
                id: FfiConverterString.read(from: &buf), 
                createdAt: FfiConverterString.read(from: &buf), 
                scheduledStart: FfiConverterOptionString.read(from: &buf), 
                scheduledEnd: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: LayoutPage, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.createdAt, into: &buf)
        FfiConverterOptionString.write(value.scheduledStart, into: &buf)
        FfiConverterOptionString.write(value.scheduledEnd, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLayoutPage_lift(_ buf: RustBuffer) throws -> LayoutPage {
    return try FfiConverterTypeLayoutPage.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLayoutPage_lower(_ value: LayoutPage) -> RustBuffer {
    return FfiConverterTypeLayoutPage.lower(value)
}


/**
 * One expanded occurrence of a recurring series.
 */
public struct Occurrence: Equatable, Hashable {
    /**
     * The rule's own occurrence date (`YYYY-MM-DD`), used to match skips and
     * overrides. Always date-only, even for a timed series.
     */
    public var originalDate: String
    public var scheduledStart: String
    public var scheduledEnd: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * The rule's own occurrence date (`YYYY-MM-DD`), used to match skips and
         * overrides. Always date-only, even for a timed series.
         */originalDate: String, scheduledStart: String, scheduledEnd: String?) {
        self.originalDate = originalDate
        self.scheduledStart = scheduledStart
        self.scheduledEnd = scheduledEnd
    }

    

    
}

#if compiler(>=6)
extension Occurrence: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeOccurrence: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Occurrence {
        return
            try Occurrence(
                originalDate: FfiConverterString.read(from: &buf), 
                scheduledStart: FfiConverterString.read(from: &buf), 
                scheduledEnd: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: Occurrence, into buf: inout [UInt8]) {
        FfiConverterString.write(value.originalDate, into: &buf)
        FfiConverterString.write(value.scheduledStart, into: &buf)
        FfiConverterOptionString.write(value.scheduledEnd, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeOccurrence_lift(_ buf: RustBuffer) throws -> Occurrence {
    return try FfiConverterTypeOccurrence.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeOccurrence_lower(_ value: Occurrence) -> RustBuffer {
    return FfiConverterTypeOccurrence.lower(value)
}


/**
 * Result of moving a schedule's start. `end` of `None` is a single occurrence.
 */
public struct ScheduleTransition: Equatable, Hashable {
    public var start: String
    public var end: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(start: String, end: String?) {
        self.start = start
        self.end = end
    }

    

    
}

#if compiler(>=6)
extension ScheduleTransition: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeScheduleTransition: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ScheduleTransition {
        return
            try ScheduleTransition(
                start: FfiConverterString.read(from: &buf), 
                end: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: ScheduleTransition, into buf: inout [UInt8]) {
        FfiConverterString.write(value.start, into: &buf)
        FfiConverterOptionString.write(value.end, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeScheduleTransition_lift(_ buf: RustBuffer) throws -> ScheduleTransition {
    return try FfiConverterTypeScheduleTransition.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeScheduleTransition_lower(_ value: ScheduleTransition) -> RustBuffer {
    return FfiConverterTypeScheduleTransition.lower(value)
}


/**
 * Structural placement of one timed event within a day.
 *
 * Carries no pixels. The cascade column says which lane the event occupies;
 * turning that into a frame is the renderer's job, and iOS should do it with
 * its own metrics rather than inherit the desktop's.
 */
public struct TimedBlock: Equatable, Hashable {
    public var pageId: String
    /**
     * Sweep-line column: 0 is the cluster host, deeper values cascade over it.
     */
    public var cascadeDepth: UInt32
    public var isContinuationBefore: Bool
    public var isContinuationAfter: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(pageId: String, 
        /**
         * Sweep-line column: 0 is the cluster host, deeper values cascade over it.
         */cascadeDepth: UInt32, isContinuationBefore: Bool, isContinuationAfter: Bool) {
        self.pageId = pageId
        self.cascadeDepth = cascadeDepth
        self.isContinuationBefore = isContinuationBefore
        self.isContinuationAfter = isContinuationAfter
    }

    

    
}

#if compiler(>=6)
extension TimedBlock: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTimedBlock: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TimedBlock {
        return
            try TimedBlock(
                pageId: FfiConverterString.read(from: &buf), 
                cascadeDepth: FfiConverterUInt32.read(from: &buf), 
                isContinuationBefore: FfiConverterBool.read(from: &buf), 
                isContinuationAfter: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: TimedBlock, into buf: inout [UInt8]) {
        FfiConverterString.write(value.pageId, into: &buf)
        FfiConverterUInt32.write(value.cascadeDepth, into: &buf)
        FfiConverterBool.write(value.isContinuationBefore, into: &buf)
        FfiConverterBool.write(value.isContinuationAfter, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTimedBlock_lift(_ buf: RustBuffer) throws -> TimedBlock {
    return try FfiConverterTypeTimedBlock.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTimedBlock_lower(_ value: TimedBlock) -> RustBuffer {
    return FfiConverterTypeTimedBlock.lower(value)
}


/**
 * A parsed `pikos://` link.
 */

public enum DeepLink: Equatable, Hashable {
    
    case page(pageId: String
    )
    case view(viewId: SmartView
    )
    case calendar
    case quickAdd(prefill: String
    )
    case search(prefill: String
    )





}

#if compiler(>=6)
extension DeepLink: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDeepLink: FfiConverterRustBuffer {
    typealias SwiftType = DeepLink

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DeepLink {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .page(pageId: try FfiConverterString.read(from: &buf)
        )
        
        case 2: return .view(viewId: try FfiConverterTypeSmartView.read(from: &buf)
        )
        
        case 3: return .calendar
        
        case 4: return .quickAdd(prefill: try FfiConverterString.read(from: &buf)
        )
        
        case 5: return .search(prefill: try FfiConverterString.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: DeepLink, into buf: inout [UInt8]) {
        switch value {
        
        
        case let .page(pageId):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(pageId, into: &buf)
            
        
        case let .view(viewId):
            writeInt(&buf, Int32(2))
            FfiConverterTypeSmartView.write(viewId, into: &buf)
            
        
        case .calendar:
            writeInt(&buf, Int32(3))
        
        
        case let .quickAdd(prefill):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(prefill, into: &buf)
            
        
        case let .search(prefill):
            writeInt(&buf, Int32(5))
            FfiConverterString.write(prefill, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDeepLink_lift(_ buf: RustBuffer) throws -> DeepLink {
    return try FfiConverterTypeDeepLink.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDeepLink_lower(_ value: DeepLink) -> RustBuffer {
    return FfiConverterTypeDeepLink.lower(value)
}




public enum SmartView: Equatable, Hashable {
    
    case today
    case inbox





}

#if compiler(>=6)
extension SmartView: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSmartView: FfiConverterRustBuffer {
    typealias SwiftType = SmartView

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SmartView {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .today
        
        case 2: return .inbox
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: SmartView, into buf: inout [UInt8]) {
        switch value {
        
        
        case .today:
            writeInt(&buf, Int32(1))
        
        
        case .inbox:
            writeInt(&buf, Int32(2))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSmartView_lift(_ buf: RustBuffer) throws -> SmartView {
    return try FfiConverterTypeSmartView.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSmartView_lower(_ value: SmartView) -> RustBuffer {
    return FfiConverterTypeSmartView.lower(value)
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeOccurrence: FfiConverterRustBuffer {
    typealias SwiftType = Occurrence?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeOccurrence.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeOccurrence.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeDeepLink: FfiConverterRustBuffer {
    typealias SwiftType = DeepLink?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeDeepLink.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeDeepLink.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeAllDayBar: FfiConverterRustBuffer {
    typealias SwiftType = [AllDayBar]

    public static func write(_ value: [AllDayBar], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeAllDayBar.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [AllDayBar] {
        let len: Int32 = try readInt(&buf)
        var seq = [AllDayBar]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeAllDayBar.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeLayoutPage: FfiConverterRustBuffer {
    typealias SwiftType = [LayoutPage]

    public static func write(_ value: [LayoutPage], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeLayoutPage.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [LayoutPage] {
        let len: Int32 = try readInt(&buf)
        var seq = [LayoutPage]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeLayoutPage.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeOccurrence: FfiConverterRustBuffer {
    typealias SwiftType = [Occurrence]

    public static func write(_ value: [Occurrence], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeOccurrence.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Occurrence] {
        let len: Int32 = try readInt(&buf)
        var seq = [Occurrence]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeOccurrence.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeTimedBlock: FfiConverterRustBuffer {
    typealias SwiftType = [TimedBlock]

    public static func write(_ value: [TimedBlock], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeTimedBlock.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [TimedBlock] {
        let len: Int32 = try readInt(&buf)
        var seq = [TimedBlock]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeTimedBlock.read(from: &buf))
        }
        return seq
    }
}
/**
 * Carry a series' end onto a new start, preserving duration.
 *
 * `None` when either side is all-day. An end earlier than the start means an
 * overnight event, so the end lands on the following day.
 */
public func computeNextEnd(baseEnd: String, nextStart: String) -> String?  {
    return try!  FfiConverterOptionString.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_pikos_ffi_fn_func_compute_next_end(
        FfiConverterString.lower(baseEnd),
        FfiConverterString.lower(nextStart),uniffiCallStatus
    )
})
}
/**
 * Decide what happens to an event's end when its start moves to `iso`.
 */
public func computeScheduleTransition(currentStart: String?, currentEnd: String?, iso: String) -> ScheduleTransition  {
    return try!  FfiConverterTypeScheduleTransition_lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_pikos_ffi_fn_func_compute_schedule_transition(
        FfiConverterOptionString.lower(currentStart),
        FfiConverterOptionString.lower(currentEnd),
        FfiConverterString.lower(iso),uniffiCallStatus
    )
})
}
/**
 * The Tiptap document schema this build writes.
 *
 * Exposed so the iOS app can refuse to save over a page whose
 * `contentSchemaVersion` exceeds its own — re-serialising through an older
 * editor schema silently drops node types it cannot represent, which is the
 * corruption mode a second writing client introduces.
 */
public func contentSchemaVersion() -> Int64  {
    return try!  FfiConverterInt64.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_pikos_ffi_fn_func_content_schema_version(uniffiCallStatus
    )
})
}
/**
 * Midnight boundaries strictly between two wall-clock datetimes. An event
 * ending exactly at midnight touches the boundary without crossing it.
 */
public func countCrossingMidnights(start: String, end: String) -> UInt32  {
    return try!  FfiConverterUInt32.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_pikos_ffi_fn_func_count_crossing_midnights(
        FfiConverterString.lower(start),
        FfiConverterString.lower(end),uniffiCallStatus
    )
})
}
/**
 * Expand a rule into occurrences within `[range_start, range_end)`.
 */
public func expandRecurrence(rrule: String, scheduledStart: String, scheduledEnd: String?, exdates: [String], rangeStart: String, rangeEnd: String) -> [Occurrence]  {
    return try!  FfiConverterSequenceTypeOccurrence.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_pikos_ffi_fn_func_expand_recurrence(
        FfiConverterString.lower(rrule),
        FfiConverterString.lower(scheduledStart),
        FfiConverterOptionString.lower(scheduledEnd),
        FfiConverterSequenceString.lower(exdates),
        FfiConverterString.lower(rangeStart),
        FfiConverterString.lower(rangeEnd),uniffiCallStatus
    )
})
}
/**
 * Plain text of a Tiptap document, for the full-text index.
 *
 * iOS calls this on the editor webview's `docChanged` message so search keeps
 * working for anything typed on the phone — the ProseMirror JSON itself is not
 * searchable. Never fails: malformed content yields an empty string rather
 * than blocking the save, because an unsearchable page beats an unsaveable one.
 */
public func extractText(docJson: String) -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_pikos_ffi_fn_func_extract_text(
        FfiConverterString.lower(docJson),uniffiCallStatus
    )
})
}
/**
 * All-day bars for `days` (each a `YYYY-MM-DD`), with rows stable across the
 * full span of any event overlapping the range — so a multi-week event keeps
 * its row in every week it appears.
 */
public func layoutAllDay(pages: [LayoutPage], days: [String]) -> [AllDayBar]  {
    return try!  FfiConverterSequenceTypeAllDayBar.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_pikos_ffi_fn_func_layout_all_day(
        FfiConverterSequenceTypeLayoutPage.lower(pages),
        FfiConverterSequenceString.lower(days),uniffiCallStatus
    )
})
}
/**
 * Cascade columns for every timed event touching `day` (a `YYYY-MM-DD`).
 */
public func layoutTimedDay(pages: [LayoutPage], day: String) -> [TimedBlock]  {
    return try!  FfiConverterSequenceTypeTimedBlock.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_pikos_ffi_fn_func_layout_timed_day(
        FfiConverterSequenceTypeLayoutPage.lower(pages),
        FfiConverterString.lower(day),uniffiCallStatus
    )
})
}
/**
 * Next occurrence strictly after `after_date`, skipping `exdates`.
 *
 * `None` when the series is exhausted, the rule or start is malformed, or
 * every candidate within the internal bound is excluded.
 */
public func nextOccurrenceAfter(rrule: String, scheduledStart: String, afterDate: String, exdates: [String]) -> Occurrence?  {
    return try!  FfiConverterOptionTypeOccurrence.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_pikos_ffi_fn_func_next_occurrence_after(
        FfiConverterString.lower(rrule),
        FfiConverterString.lower(scheduledStart),
        FfiConverterString.lower(afterDate),
        FfiConverterSequenceString.lower(exdates),uniffiCallStatus
    )
})
}
/**
 * Normalise an end-date picker result. `None` means a single-day event.
 */
public func normalizeEndInput(currentStart: String, endIso: String?) -> String?  {
    return try!  FfiConverterOptionString.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_pikos_ffi_fn_func_normalize_end_input(
        FfiConverterString.lower(currentStart),
        FfiConverterOptionString.lower(endIso),uniffiCallStatus
    )
})
}
/**
 * Parse a `pikos://` URL. Returns `None` for anything unrecognised; callers
 * should treat that as a no-op, since deep links arrive from outside the app.
 */
public func parseDeepLink(url: String) -> DeepLink?  {
    return try!  FfiConverterOptionTypeDeepLink.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_pikos_ffi_fn_func_parse_deep_link(
        FfiConverterString.lower(url),uniffiCallStatus
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_pikos_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_pikos_ffi_checksum_func_compute_next_end() != 15190) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pikos_ffi_checksum_func_compute_schedule_transition() != 52600) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pikos_ffi_checksum_func_content_schema_version() != 85) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pikos_ffi_checksum_func_count_crossing_midnights() != 13105) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pikos_ffi_checksum_func_expand_recurrence() != 30980) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pikos_ffi_checksum_func_extract_text() != 5206) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pikos_ffi_checksum_func_layout_all_day() != 9636) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pikos_ffi_checksum_func_layout_timed_day() != 3648) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pikos_ffi_checksum_func_next_occurrence_after() != 41709) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pikos_ffi_checksum_func_normalize_end_input() != 1242) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pikos_ffi_checksum_func_parse_deep_link() != 54718) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsurePikosFfiInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all