// Emits the Swift half of the editor bridge from src/protocol.ts.
//
// Both sides of the bridge are generated from one declaration so they cannot
// drift. See the note at the top of src/protocol.ts for why that matters: a
// mismatched field does not fail to compile, it arrives as nil and the editor
// quietly stops saving.
//
// Output is committed and re-checked in CI, the same arrangement as the UniFFI
// bindings.

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";

import type { FieldType, MessageSpec } from "../src/protocol";
import { HOST_TO_WEBVIEW, PROTOCOL_VERSION, WEBVIEW_TO_HOST } from "../src/protocol";

function packageRoot(): string {
  let dir = process.cwd();
  for (;;) {
    try {
      const pkg = JSON.parse(readFileSync(resolve(dir, "package.json"), "utf8")) as {
        name?: string;
      };
      if (pkg.name === "@pikos/editor-mobile") return dir;
    } catch {
      // keep walking
    }
    const parent = dirname(dir);
    if (parent === dir) throw new Error("run this from within packages/editor-mobile");
    dir = parent;
  }
}

/** Swift type for a declared field type. */
function swiftType(type: FieldType): string {
  switch (type) {
    case "string":
      return "String";
    case "integer":
      return "Int";
    case "number":
      return "Double";
    case "boolean":
      return "Bool";
    case "stringArray":
      return "[String]";
    case "json":
      // Documents cross as their JSON text rather than a decoded structure.
      // Swift never inspects a ProseMirror document — it stores it and hands it
      // back — so decoding it would cost a parse per keystroke and risk
      // re-serialising it differently from how the editor wrote it.
      return "String";
  }
}

function docComment(text: string, indent: string): string {
  // Wrap at a width that stays readable in Xcode's default editor.
  const words = text.split(/\s+/);
  const lines: string[] = [];
  let line = "";
  for (const word of words) {
    if (line.length + word.length + 1 > 76) {
      lines.push(line);
      line = word;
    } else {
      line = line ? `${line} ${word}` : word;
    }
  }
  if (line) lines.push(line);
  return lines.map((l) => `${indent}/// ${l}`).join("\n");
}

function structName(prefix: string, type: string): string {
  return `${prefix}${type.charAt(0).toUpperCase()}${type.slice(1)}Payload`;
}

function payloadStruct(prefix: string, type: string, spec: MessageSpec): string {
  const fields = Object.entries(spec.fields);
  const name = structName(prefix, type);
  const header = `${docComment(spec.doc, "    ")}\n    public struct ${name}: Codable, Equatable {`;

  // Public, with an explicit public initialiser. Swift synthesises only an
  // internal memberwise init for a public struct, and these appear as
  // associated values on a public enum, so callers outside the module could
  // otherwise decode them but never construct one.
  if (fields.length === 0) {
    return `${header}\n        public init() {}\n    }`;
  }
  const properties = fields
    .map(([field, fieldType]) => `        public let ${field}: ${swiftType(fieldType)}`)
    .join("\n");
  const params = fields
    .map(([field, fieldType]) => `${field}: ${swiftType(fieldType)}`)
    .join(", ");
  const assignments = fields
    .map(([field]) => `            self.${field} = ${field}`)
    .join("\n");
  return [
    header,
    properties,
    "",
    `        public init(${params}) {`,
    assignments,
    "        }",
    "    }",
  ].join("\n");
}

function main(): void {
  const root = packageRoot();
  const out = resolve(root, "../../apps/ios/PikosEditorBridge/Sources/PikosEditorBridge");

  const hostStructs = Object.entries(HOST_TO_WEBVIEW)
    .map(([type, spec]) => payloadStruct("Outgoing", type, spec))
    .join("\n\n");
  const webviewStructs = Object.entries(WEBVIEW_TO_HOST)
    .map(([type, spec]) => payloadStruct("Incoming", type, spec))
    .join("\n\n");

  const incomingCases = Object.entries(WEBVIEW_TO_HOST)
    .map(([type]) => `        case ${type}(${structName("Incoming", type)})`)
    .join("\n");

  const decodeCases = Object.entries(WEBVIEW_TO_HOST)
    .map(
      ([type]) => `            case "${type}":
                return .${type}(try container.decode(${structName("Incoming", type)}.self, forKey: .payload))`
    )
    .join("\n");

  const swift = `// Generated by packages/editor-mobile/scripts/gen-swift-protocol.ts
// Do not edit. Run \`pnpm --filter @pikos/editor-mobile gen:swift\` after
// changing packages/editor-mobile/src/protocol.ts.
//
// Both halves of the editor bridge come from that one declaration, so the
// webview and the host cannot disagree about a field name or a type. A
// mismatch there would not fail to compile — it would arrive as nil and the
// editor would quietly stop saving.

import Foundation

/// The editor bridge's wire protocol.
public enum EditorBridge {
    /// Version carried on every message.
    ///
    /// On the envelope rather than negotiated once at startup: an app update
    /// can replace the native shell while a webview is still live, so the
    /// receiver needs to be able to reject an individual message it does not
    /// understand instead of misreading it.
    public static let protocolVersion = ${PROTOCOL_VERSION}

    // MARK: - Host → webview

${hostStructs}

    /// A message the host sends into the editor.
    ///
    /// Encodes to \`{ "v": 1, "type": "...", "payload": { ... } }\`.
    public enum Outgoing {
${Object.entries(HOST_TO_WEBVIEW)
  .map(([type]) => `        case ${type}(${structName("Outgoing", type)})`)
  .join("\n")}

        var messageType: String {
            switch self {
${Object.entries(HOST_TO_WEBVIEW)
  .map(([type]) => `            case .${type}: return "${type}"`)
  .join("\n")}
            }
        }

        /// The JSON text to hand to \`evaluateJavaScript\`.
        public func encoded() throws -> String {
            let encoder = JSONEncoder()
            // Stable key order keeps messages diffable in logs, which matters
            // when debugging a bridge you cannot step through.
            encoder.outputFormatting = [.sortedKeys]

            let payloadData: Data
            switch self {
${Object.entries(HOST_TO_WEBVIEW)
  .map(([type]) => `            case .${type}(let p): payloadData = try encoder.encode(p)`)
  .join("\n")}
            }

            let payloadJSON = String(decoding: payloadData, as: UTF8.self)
            let escapedType = messageType
            return "{\\"v\\":\\(EditorBridge.protocolVersion),\\"type\\":\\"\\(escapedType)\\",\\"payload\\":\\(payloadJSON)}"
        }
    }

    // MARK: - Webview → host

${webviewStructs}

    /// A message the editor sends to the host.
    public enum Incoming: Decodable {
${incomingCases}

        private enum CodingKeys: String, CodingKey {
            case v, type, payload
        }

        public enum DecodingFailure: Error, Equatable {
            /// The webview speaks a protocol version this build does not.
            case unsupportedVersion(Int)
            /// A message type this build does not know.
            case unknownType(String)
        }

        public init(from decoder: Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)

            let version = try container.decode(Int.self, forKey: .v)
            guard version == EditorBridge.protocolVersion else {
                throw DecodingFailure.unsupportedVersion(version)
            }

            let type = try container.decode(String.self, forKey: .type)
            switch type {
${decodeCases}
            default:
                throw DecodingFailure.unknownType(type)
            }
        }
    }
}
`;

  mkdirSync(out, { recursive: true });
  writeFileSync(resolve(out, "EditorBridgeProtocol.swift"), swift);
  process.stdout.write(
    `EditorBridgeProtocol.swift: ${Object.keys(HOST_TO_WEBVIEW).length} outgoing, ` +
      `${Object.keys(WEBVIEW_TO_HOST).length} incoming\nout: ${out}\n`
  );
}

main();
