//! Cross-validation against rrule.js — the engine Pikos ran in production
//! before this crate replaced it. Fixtures are generated by
//! `scripts/gen-rrule-goldens.mjs`; every case must match byte-for-byte so
//! the migration can't silently shift a single occurrence.

use serde::Deserialize;

#[derive(Deserialize)]
struct Fixtures {
    limit: u32,
    cases: Vec<Case>,
}

#[derive(Deserialize)]
struct Case {
    rrule: String,
    dtstart: String,
    occurrences: Vec<String>,
}

#[test]
fn matches_rrule_js_goldens() {
    let fixtures: Fixtures =
        serde_json::from_str(include_str!("fixtures/rrule_js_goldens.json"))
            .expect("fixtures parse");
    assert!(!fixtures.cases.is_empty());

    let mut mismatches = Vec::new();
    for case in &fixtures.cases {
        let ours = pikos_recurrence::list_occurrences(&case.rrule, &case.dtstart, fixtures.limit);
        if ours != case.occurrences {
            mismatches.push(format!(
                "rrule={} dtstart={}\n  rrule.js: {:?}\n  engine:   {:?}",
                case.rrule, case.dtstart, case.occurrences, ours
            ));
        }
    }
    assert!(
        mismatches.is_empty(),
        "{} of {} cases diverge from rrule.js:\n{}",
        mismatches.len(),
        fixtures.cases.len(),
        mismatches.join("\n")
    );
}
