// Synchronous entry point for the Pikos recurrence engine.
//
// The wasm binary ships base64-embedded (pkg/wasm_data.js, generated by
// scripts/build-recurrence-wasm.sh) and is instantiated here at module-import
// time, so every export is callable synchronously in any runtime — browser,
// vite bundle, vitest, esbuild-bundled node — with zero loader plumbing.
// Decode + instantiation of the ~200KB module is a few milliseconds, paid
// once per process.

import { initSync } from "./pkg/pikos_recurrence_wasm.js";
import { WASM_BASE64 } from "./pkg/wasm_data.js";

function decodeBase64(b64) {
  // Node exposes Buffer (fast path); browsers decode via atob.
  if (typeof Buffer !== "undefined") {
    return Buffer.from(b64, "base64");
  }
  const binary = atob(b64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) {
    bytes[i] = binary.charCodeAt(i);
  }
  return bytes;
}

initSync({ module: decodeBase64(WASM_BASE64) });

export {
  alignWeeklyRuleToAnchor,
  buildRrule,
  computeNextEnd,
  expandRange,
  listOccurrences,
  missedOccurrencesBetween,
  nextOccurrenceAfter,
  parseRruleOptions,
  rruleToLabel,
  rruleToShortLabel,
  snapAnchorToRule,
} from "./pkg/pikos_recurrence_wasm.js";
