#!/usr/bin/env bash
# Builds the @pikos/recurrence-wasm package from the Rust recurrence engine.
#
# Pipeline:
#   crates/pikos-recurrence        (engine)
#   └─ crates/pikos-recurrence-wasm (wasm-bindgen bindings)
#      └─ packages/recurrence-wasm/pkg (generated JS glue + embedded wasm)
#
# The generated pkg/ is COMMITTED so JS-only development (vite, vitest,
# esbuild) never needs a Rust toolchain. Re-run this script whenever the
# engine or bindings change, and commit the regenerated pkg/.
#
# Requirements: Docker. No local Rust toolchain, and no wasm-bindgen CLI.
#
# The compile runs inside a pinned Linux image because rustc's wasm output
# depends on the HOST it runs on, which no compiler flag can pin away. Measured
# on rustc 1.93.1 (same commit, same LLVM 21.1.8, codegen-units=1, fat LTO):
# aarch64-apple-darwin emits 269,840 bytes and x86_64-unknown-linux-gnu emits
# 269,030 — same exports, same strings, 810 bytes of different codegen. Each
# host is perfectly reproducible with itself, so the artifact only round-trips
# if every machine compiles on the same one. An earlier version of this script
# pinned rustc and remapped paths and built natively; those pins are still here
# and still necessary, but they cannot reach the host, so the committed pkg was
# only ever reproducible on the Mac that produced it.

set -euo pipefail
cd "$(dirname "$0")/.."

PKG_DIR="packages/recurrence-wasm/pkg"
WASM_BINDGEN_PIN=$(sed -n 's/^wasm-bindgen = "=\(.*\)"$/\1/p' crates/pikos-recurrence-wasm/Cargo.toml)

# Tracking `stable` would go red the day rustc bumps: its version moves codegen
# and the panic line tables. The image tag pins toolchain and host in one value.
RUSTC_PIN="1.93.1"
BUILD_IMAGE="rust:${RUSTC_PIN}-slim"
BUILD_PLATFORM="linux/amd64"

if ! docker info >/dev/null 2>&1; then
  echo "Docker is required: the artifact is only reproducible when compiled" >&2
  echo "inside ${BUILD_IMAGE} (${BUILD_PLATFORM}). Start Docker and retry." >&2
  exit 1
fi

docker run --rm \
  --platform "$BUILD_PLATFORM" \
  -v "$PWD:/work" \
  -w /work \
  -e PKG_DIR="$PKG_DIR" \
  -e WASM_BINDGEN_PIN="$WASM_BINDGEN_PIN" \
  -e HOST_OWNER="$(id -u):$(id -g)" \
  "$BUILD_IMAGE" \
  bash -euo pipefail -c '
    apt-get update -qq >/dev/null
    apt-get install -y -qq curl ca-certificates >/dev/null
    rustup target add wasm32-unknown-unknown >/dev/null

    curl -fsSL "https://github.com/wasm-bindgen/wasm-bindgen/releases/download/${WASM_BINDGEN_PIN}/wasm-bindgen-${WASM_BINDGEN_PIN}-x86_64-unknown-linux-musl.tar.gz" \
      | tar xz --strip-components=1 -C /usr/local/bin
    CLI_VERSION=$(wasm-bindgen --version | awk "{print \$2}")
    if [ "$CLI_VERSION" != "$WASM_BINDGEN_PIN" ]; then
      echo "wasm-bindgen CLI ${CLI_VERSION} != pinned ${WASM_BINDGEN_PIN}" >&2
      exit 1
    fi

    # Outside the mount: the host target/ holds objects fingerprinted for a
    # different host, and sharing the directory lets them collide.
    export CARGO_TARGET_DIR=/tmp/target

    # Panic locations bake in source paths carrying $HOME and the host triple;
    # ambient RUSTFLAGS would do the same. Both get fixed stand-ins.
    export RUSTFLAGS="--remap-path-prefix=${CARGO_HOME:-$HOME/.cargo}/registry/src=/cargo --remap-path-prefix=$(rustc --print sysroot)=/rustc"

    cargo build \
      -p pikos-recurrence-wasm \
      --target wasm32-unknown-unknown \
      --profile wasm-release

    rm -rf "$PKG_DIR"
    wasm-bindgen \
      --target web \
      --out-dir "$PKG_DIR" \
      "$CARGO_TARGET_DIR/wasm32-unknown-unknown/wasm-release/pikos_recurrence_wasm.wasm"

    chown -R "$HOST_OWNER" "$PKG_DIR"
  '

# Embed the wasm as base64 so consumers initialize synchronously at import time
# with zero bundler config. Host-side: a pure function of bytes already fixed.
node - "$PKG_DIR" <<'EOF'
const fs = require("fs");
const path = require("path");
const pkgDir = process.argv[2];
const wasmPath = path.join(pkgDir, "pikos_recurrence_wasm_bg.wasm");
const b64 = fs.readFileSync(wasmPath).toString("base64");
fs.writeFileSync(
  path.join(pkgDir, "wasm_data.js"),
  "// Generated by scripts/build-recurrence-wasm.sh — do not edit.\n" +
    "// Base64 of pikos_recurrence_wasm_bg.wasm, embedded so the engine\n" +
    "// initializes synchronously in every runtime without asset plumbing.\n" +
    `export const WASM_BASE64 =\n  "${b64}";\n`
);
fs.writeFileSync(
  path.join(pkgDir, "wasm_data.d.ts"),
  "export declare const WASM_BASE64: string;\n"
);
// The raw .wasm is not shipped — the base64 module above is the artifact.
fs.unlinkSync(wasmPath);
const gitignore = path.join(pkgDir, ".gitignore");
if (fs.existsSync(gitignore)) fs.unlinkSync(gitignore);
console.log(`embedded ${(b64.length / 1024).toFixed(0)}KB base64 into ${pkgDir}/wasm_data.js`);
EOF

echo "OK: ${PKG_DIR} regenerated — commit the changes."
