#!/usr/bin/env bash
# Builds the @pikos/recurrence-wasm package from the Rust recurrence engine.
#
# Pipeline:
#   crates/pikos-recurrence        (engine)
#   └─ crates/pikos-recurrence-wasm (wasm-bindgen bindings)
#      └─ packages/recurrence-wasm/pkg (generated JS glue + embedded wasm)
#
# The generated pkg/ is COMMITTED so JS-only development (vite, vitest,
# esbuild) never needs a Rust toolchain. Re-run this script whenever the
# engine or bindings change, and commit the regenerated pkg/.
#
# Requirements:
#   - rustup (the pinned toolchain and the wasm32 target install on demand)
#   - wasm-bindgen CLI matching the version pinned in
#     crates/pikos-recurrence-wasm/Cargo.toml
#     (cargo install wasm-bindgen-cli --version <pin>, or a prebuilt release)

set -euo pipefail
cd "$(dirname "$0")/.."

PKG_DIR="packages/recurrence-wasm/pkg"
WASM_BINDGEN_PIN=$(sed -n 's/^wasm-bindgen = "=\(.*\)"$/\1/p' crates/pikos-recurrence-wasm/Cargo.toml)

# CI re-runs this script and fails on any diff against the committed pkg/, so
# the output has to be byte-identical on every machine that builds it. rustc's
# version moves both codegen and the embedded panic line tables, so tracking
# `stable` would go red the day it bumps and stay red while a developer's rustc
# and CI's disagree. Those panic locations also bake in source paths carrying
# $HOME and the host triple — remapped to fixed stand-ins below, as is any
# ambient RUSTFLAGS, for the same reason.
RUSTC_PIN="1.93.1"

if ! command -v wasm-bindgen >/dev/null; then
  echo "wasm-bindgen CLI not found. Install with:" >&2
  echo "  cargo install wasm-bindgen-cli --version ${WASM_BINDGEN_PIN}" >&2
  exit 1
fi

CLI_VERSION=$(wasm-bindgen --version | awk '{print $2}')
if [ "$CLI_VERSION" != "$WASM_BINDGEN_PIN" ]; then
  echo "wasm-bindgen CLI ${CLI_VERSION} != pinned ${WASM_BINDGEN_PIN} in crates/pikos-recurrence-wasm/Cargo.toml" >&2
  exit 1
fi

export RUSTUP_TOOLCHAIN="$RUSTC_PIN"
rustup toolchain install "$RUSTC_PIN" \
  --profile minimal \
  --target wasm32-unknown-unknown \
  --no-self-update >/dev/null

export RUSTFLAGS="--remap-path-prefix=${CARGO_HOME:-$HOME/.cargo}/registry/src=/cargo --remap-path-prefix=$(rustc --print sysroot)=/rustc"

cargo build \
  -p pikos-recurrence-wasm \
  --target wasm32-unknown-unknown \
  --profile wasm-release

rm -rf "$PKG_DIR"
wasm-bindgen \
  --target web \
  --out-dir "$PKG_DIR" \
  target/wasm32-unknown-unknown/wasm-release/pikos_recurrence_wasm.wasm

# Embed the wasm as base64 so consumers initialize synchronously at import
# time with zero bundler configuration (vite, vitest, esbuild, plain node).
node - "$PKG_DIR" <<'EOF'
const fs = require("fs");
const path = require("path");
const pkgDir = process.argv[2];
const wasmPath = path.join(pkgDir, "pikos_recurrence_wasm_bg.wasm");
const b64 = fs.readFileSync(wasmPath).toString("base64");
fs.writeFileSync(
  path.join(pkgDir, "wasm_data.js"),
  "// Generated by scripts/build-recurrence-wasm.sh — do not edit.\n" +
    "// Base64 of pikos_recurrence_wasm_bg.wasm, embedded so the engine\n" +
    "// initializes synchronously in every runtime without asset plumbing.\n" +
    `export const WASM_BASE64 =\n  "${b64}";\n`
);
fs.writeFileSync(
  path.join(pkgDir, "wasm_data.d.ts"),
  "export declare const WASM_BASE64: string;\n"
);
// The raw .wasm is not shipped — the base64 module above is the artifact.
fs.unlinkSync(wasmPath);
const gitignore = path.join(pkgDir, ".gitignore");
if (fs.existsSync(gitignore)) fs.unlinkSync(gitignore);
console.log(`embedded ${(b64.length / 1024).toFixed(0)}KB base64 into ${pkgDir}/wasm_data.js`);
EOF

echo "OK: ${PKG_DIR} regenerated — commit the changes."
