// swift-tools-version: 5.9
import PackageDescription

// PikosCore — the shared Rust logic (crates/pikos-core), surfaced to Swift.
//
// Two halves, produced by two scripts:
//
//   Sources/PikosCore/PikosCore.swift   generated by scripts/gen-swift-bindings.sh.
//                                       Runs anywhere; committed and diffed in CI.
//   Frameworks/PikosFFI.xcframework     built by scripts/build-ios-framework.sh.
//                                       Needs a Mac, so it is NOT committed —
//                                       it is a build artifact, and a binary one.
//
// Consequence worth knowing before the first checkout: this package does not
// build until the XCFramework exists. Run scripts/build-ios-framework.sh once
// on a Mac and it will. That split is deliberate — it keeps a multi-megabyte
// binary out of git while still letting the Swift API be reviewed in a pull
// request like any other source.
let package = Package(
    name: "PikosCore",
    // iOS 17 per the plan's recommendation: modern SwiftUI plus interactive
    // WidgetKit, both of which M4 depends on.
    platforms: [.iOS(.v17), .macOS(.v14)],
    products: [
        .library(name: "PikosCore", targets: ["PikosCore"]),
        .library(name: "PikosSupport", targets: ["PikosSupport"]),
    ],
    targets: [
        .binaryTarget(
            name: "PikosFFI",
            path: "Frameworks/PikosFFI.xcframework"
        ),
        .target(
            name: "PikosCore",
            dependencies: ["PikosFFI"],
            path: "Sources/PikosCore"
        ),
        // Hand-written, and separate from the generated target on purpose:
        // Sources/PikosCore is overwritten by scripts/gen-swift-bindings.sh, and
        // anything living there would be lost on the next generation.
        //
        // It is a target rather than app code because the widget and share
        // extensions are separate processes that need the same answer about
        // where the workspace lives — and disagreeing about that means a widget
        // reading a different database from the app.
        .target(
            name: "PikosSupport",
            path: "Sources/PikosSupport"
        ),
        .testTarget(
            name: "PikosCoreTests",
            dependencies: ["PikosCore"],
            path: "Tests/PikosCoreTests"
        ),
        // Separate from PikosCoreTests because PikosSupport is a separate
        // target, and because these need nothing linked: no XCFramework, no
        // database, no device. `swift test` runs them on the host in under a
        // second, which is the point of putting the calendar's geometry here
        // rather than in the app.
        .testTarget(
            name: "PikosSupportTests",
            dependencies: ["PikosSupport"],
            path: "Tests/PikosSupportTests"
        ),
    ]
)
